name: Documentation 
description: |
  There is something that needs to be added or fixed on docs.vmst.io.
labels: ["Documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reaching out to us to request an update or change to the documentation.
  - type: textarea
    attributes:
      label: |
        Please let us know what you would like to add or change?
      description: |
        Use as much detail as possible.
      value: |
        If you are requesting to update or delete sections of existing documentation? Please provide the URL as part of your description.
    validations:
      required: true
