theme: PaperModX
relativeURLs: true
baseURL: 'https://docs.vmst.io'
title: docs·vmst·io
author: vmst·io
copyright: Copyright © 2022 vmst·io Team
languageCode: en
paginate: 5
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
DefaultContentLanguage: en

outputs:
  home:
      - HTML
      - RSS
      - JSON # is necessary

menu:
  main:
#    - identifier: home
#      name: Home
#      url: /
#      weight: 1
    - identifier: search
      name: Search
      url: /search
      weight: 2
    - identifier: docs
      name: Docs
      url: '/tags/docs'
      weight: 4
    - identifier: fund
      name: Funding
      url: '/funding'
      weight: 4
    - identifier: rules
      name: Rules
      url: '/rules'
      weight: 5
    - identifier: staff
      name: Staff
      url: '/staff'
      weight: 6
    - identifier: archives
      name: Archives
      url: '/archives'
      weight: 7
      
privacy:
  vimeo:
    disabled: false
    simple: true
  
  twitter:
    disabled: true
    
  youtube:
    disabled: false
    privacyEnhanced: true
    
minify:
  disableXML: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false

params:
  ShowCodeCopyButtons: true
  defaultTheme: auto
  disableThemeToggle: false
  TocSide: 'left'
  EnableInstantClick: true
  ShowReadingTime: false
  ShowWordCount: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  EnableImageZoom: true
  ShowToc: true
  TocOpen: true
  homeInfoParams:
      Title: "Mastodon for respectful technologists, geeks and nerds of every type and stripe."
      Content: |
        Why choose vmst.io as your Mastodon instance?
        - We respect your fundamental right to privacy. We have an [A+ rating from Mozilla Observatory](https://observatory.mozilla.org/analyze/vmst.io), have [no ads, third party cookies or trackers](https://themarkup.org/blacklight) and use the best possible TLS encryption for all connections as [verified by Cryptcheck](https://cryptcheck.fr/https/vmst.io) and [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=vmst.io).
        - We're highly available, and take ownership of issues when we're not. We publish [our realtime system status](https://status.vmst.io), and have a better than 99% observed availibility from Instances.social.
        - We are well moderated, with multiple volunteer [staffers around the world](/staff) monitoring for user reports, and clear [rules against hate speech and harrassment](/rules).

  socialIcons:
  - name: github-simple
    url: "https://github.com/vmstan/vmstio"

  editPost:
    URL: "https://github.com/vmstan/vmstio/tree/main/docs.vmst.io/content"
    Text: "Suggest Changes"
    appendFilePath: true