theme: PaperModX
relativeURLs: true
baseURL: 'https://docs.vmst.io'
title: docs·vmst·io
author: vmst·io
copyright: Copyright © 2022 vmst·io Team
languageCode: en
paginate: 5
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
DefaultContentLanguage: en

outputs:
  home:
      - HTML
      - RSS
      - JSON # is necessary

menu:
  main:
#    - identifier: home
#      name: Home
#      url: /
#      weight: 1
    - identifier: search
      name: Search
      url: /search
      weight: 2
    - identifier: docs
      name: Docs
      url: '/tags/docs'
      weight: 4
    - identifier: fund
      name: Funding
      url: '/funding'
      weight: 4
    - identifier: rules
      name: Rules
      url: '/rules'
      weight: 5
    - identifier: staff
      name: Staff
      url: '/staff'
      weight: 6
    - identifier: archives
      name: Archives
      url: '/archives'
      weight: 7
      
privacy:
  vimeo:
    disabled: false
    simple: true
  
  twitter:
    disabled: true
    
  youtube:
    disabled: false
    privacyEnhanced: true
    
minify:
  disableXML: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false

params:
  ShowCodeCopyButtons: true
  defaultTheme: auto
  disableThemeToggle: true
  TocSide: 'left'
  EnableInstantClick: true
  ShowReadingTime: false
  ShowWordCount: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  EnableImageZoom: true
  ShowToc: true
  TocOpen: true
  homeInfoParams:
      Title: "Mastodon for respectful technologists, geeks and nerds of every type and stripe."
      Content: |
        Your social media feed should be filled with what matters to you most, not what a corporation thinks you should see. Mastodon is radically different social media, back in the hands of the people. Mastodon treats you like a person, not a product.

#  socialIcons: # optional
#    - name: rss-simple
#      url: "index.xml"
#     - name: github-simple
#      url: "https://github.com/vmstan/vmstio"
#    - name: mastodon
#      url: "https://vmst.io"
  editPost:
    URL: "https://github.com/vmstan/vmstio/tree/main/docs.vmst.io/content"
    Text: "Suggest Changes"
    appendFilePath: true