theme: PaperModXRand
relativeURLs: true
baseURL: ''
title: docs·vmst·io
author: vmst·io
copyright: Copyright © 2022-2023 vmst·io Team
languageCode: en
paginate: 5
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
DefaultContentLanguage: en

outputs:
  home:
      - HTML
      - RSS
      - JSON # is necessary

menu:
  main:
#    - identifier: home
#      name: Home
#      url: /
#      weight: 1
    - identifier: search
      name: Search
      url: /search
      weight: 2
    - identifier: docs
      name: Docs
      url: '/tags/docs'
      weight: 4
    - identifier: fund
      name: Funding
      url: '/funding'
      weight: 4
    - identifier: rules
      name: Rules
      url: '/rules'
      weight: 5
    - identifier: staff
      name: Staff
      url: '/staff'
      weight: 6
    - identifier: archives
      name: Archives
      url: '/archives'
      weight: 7

frontmatter:
  date:
  - date
  - publishDate
  - lastmod
  expiryDate:
  - expiryDate
  lastmod:
  - :git
  - lastmod
  - date
  - publishDate
  publishDate:
  - publishDate
  - date

privacy:
  vimeo:
    disabled: false
    simple: true
  
  twitter:
    disabled: true
    
  youtube:
    disabled: false
    privacyEnhanced: true
    
minify:
  disableXML: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false

params:
  ShowCodeCopyButtons: true
  defaultTheme: auto
  disableThemeToggle: false
  TocSide: 'left'
  EnableInstantClick: true
  ShowReadingTime: false
  ShowWordCount: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  EnableImageZoom: false
  ShowToc: true
  TocOpen: true
  homeInfoParams:
      Title: "Mastodon for respectful technologists, geeks and nerds of every type and stripe."
      Content: |
        Why choose [vmst.io](https://vmst.io) as your Mastodon instance?
        - We are party to the [joinmastodon.org Server Covenant](https://joinmastodon.org/covenant), and active contributors to the Mastodon project and wider community.
        - We respect your fundamental right to privacy. We have an [A+ rating from Mozilla Observatory](https://observatory.mozilla.org/analyze/vmst.io), and have [no ads, third party cookies or trackers](https://themarkup.org/blacklight?url=vmst.io).
        - We're [highly available](/infrastructure), and take ownership of issues when we're not. We publish [our realtime system status](https://status.vmst.io), and have a better than 99.9% observed availability from [Instances.social](https://instances.social/vmst.io).
        - We are well moderated, with multiple volunteer [staffers around the world](/staff) monitoring for user reports, with clear [rules against hate speech and harassment](/rules).
        - Your Mastodon account here also gets you a blog on [write.vmst.io](https://write.vmst.io) and an [vmst.io account on Matrix](/matrix), all integrated through a single sign-on.
        - We host our own instances of alternative feature-rich web clients like [Elk](https://elk.vmst.io) or accessibility focused ones like [Semaphore](https://semaphore.vmst.io).

  socialIcons:
  - name: github-simple
    url: "https://github.com/vmstan/vmstio"

  editPost:
    URL: "https://github.com/vmstan/vmstio/tree/main/docs.vmst.io/content"
    Text: "Suggest Changes"
    appendFilePath: true
